// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/bidirectional/ChatServer.proto

package bidirectional

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type ChatInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatInfo) Reset()         { *m = ChatInfo{} }
func (m *ChatInfo) String() string { return proto.CompactTextString(m) }
func (*ChatInfo) ProtoMessage()    {}
func (*ChatInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f35f7a3ca38993, []int{0}
}

func (m *ChatInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatInfo.Unmarshal(m, b)
}
func (m *ChatInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatInfo.Marshal(b, m, deterministic)
}
func (m *ChatInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatInfo.Merge(m, src)
}
func (m *ChatInfo) XXX_Size() int {
	return xxx_messageInfo_ChatInfo.Size(m)
}
func (m *ChatInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChatInfo proto.InternalMessageInfo

func (m *ChatInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatInfo)(nil), "bidirectional.ChatInfo")
}

func init() {
	proto.RegisterFile("proto/bidirectional/ChatServer.proto", fileDescriptor_50f35f7a3ca38993)
}

var fileDescriptor_50f35f7a3ca38993 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xca, 0x4c, 0xc9, 0x2c, 0x4a, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0x4b, 0xcc, 0xd1,
	0x77, 0xce, 0x48, 0x2c, 0x09, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x03, 0x4b, 0x0b, 0xf1, 0xa2,
	0xc8, 0x2b, 0xc9, 0x71, 0x71, 0x80, 0x94, 0x78, 0xe6, 0xa5, 0xe5, 0x0b, 0x09, 0x71, 0xb1, 0xe4,
	0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x46, 0xfe, 0x5c, 0x5c,
	0x08, 0x23, 0x84, 0x1c, 0xb9, 0xd8, 0xdd, 0x53, 0x4b, 0x42, 0x12, 0x8b, 0xb3, 0x85, 0xc4, 0xf5,
	0x50, 0x0c, 0xd2, 0x83, 0x99, 0x22, 0x85, 0x4b, 0x42, 0x89, 0x41, 0x83, 0xd1, 0x80, 0x31, 0x89,
	0x0d, 0xec, 0x0c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0xff, 0x2d, 0xf5, 0xae, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatServerClient is the client API for ChatServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServerClient interface {
	// Sends a greeting
	GetTask(ctx context.Context, opts ...grpc.CallOption) (ChatServer_GetTaskClient, error)
}

type chatServerClient struct {
	cc *grpc.ClientConn
}

func NewChatServerClient(cc *grpc.ClientConn) ChatServerClient {
	return &chatServerClient{cc}
}

func (c *chatServerClient) GetTask(ctx context.Context, opts ...grpc.CallOption) (ChatServer_GetTaskClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatServer_serviceDesc.Streams[0], "/bidirectional.ChatServer/GetTask", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServerGetTaskClient{stream}
	return x, nil
}

type ChatServer_GetTaskClient interface {
	Send(*ChatInfo) error
	Recv() (*ChatInfo, error)
	grpc.ClientStream
}

type chatServerGetTaskClient struct {
	grpc.ClientStream
}

func (x *chatServerGetTaskClient) Send(m *ChatInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServerGetTaskClient) Recv() (*ChatInfo, error) {
	m := new(ChatInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServerServer is the server API for ChatServer service.
type ChatServerServer interface {
	// Sends a greeting
	GetTask(ChatServer_GetTaskServer) error
}

// UnimplementedChatServerServer can be embedded to have forward compatible implementations.
type UnimplementedChatServerServer struct {
}

func (*UnimplementedChatServerServer) GetTask(srv ChatServer_GetTaskServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}

func RegisterChatServerServer(s *grpc.Server, srv ChatServerServer) {
	s.RegisterService(&_ChatServer_serviceDesc, srv)
}

func _ChatServer_GetTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServerServer).GetTask(&chatServerGetTaskServer{stream})
}

type ChatServer_GetTaskServer interface {
	Send(*ChatInfo) error
	Recv() (*ChatInfo, error)
	grpc.ServerStream
}

type chatServerGetTaskServer struct {
	grpc.ServerStream
}

func (x *chatServerGetTaskServer) Send(m *ChatInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServerGetTaskServer) Recv() (*ChatInfo, error) {
	m := new(ChatInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChatServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bidirectional.ChatServer",
	HandlerType: (*ChatServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTask",
			Handler:       _ChatServer_GetTask_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/bidirectional/ChatServer.proto",
}
