// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/myproto/PurgeResult.proto

package myproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PurgeReuslt struct {
	Total                int32                `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Results              []*SinglePurgeResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PurgeReuslt) Reset()         { *m = PurgeReuslt{} }
func (m *PurgeReuslt) String() string { return proto.CompactTextString(m) }
func (*PurgeReuslt) ProtoMessage()    {}
func (*PurgeReuslt) Descriptor() ([]byte, []int) {
	return fileDescriptor_c901454c9c027c0e, []int{0}
}

func (m *PurgeReuslt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurgeReuslt.Unmarshal(m, b)
}
func (m *PurgeReuslt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurgeReuslt.Marshal(b, m, deterministic)
}
func (m *PurgeReuslt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurgeReuslt.Merge(m, src)
}
func (m *PurgeReuslt) XXX_Size() int {
	return xxx_messageInfo_PurgeReuslt.Size(m)
}
func (m *PurgeReuslt) XXX_DiscardUnknown() {
	xxx_messageInfo_PurgeReuslt.DiscardUnknown(m)
}

var xxx_messageInfo_PurgeReuslt proto.InternalMessageInfo

func (m *PurgeReuslt) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PurgeReuslt) GetResults() []*SinglePurgeResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type SinglePurgeResult struct {
	PurgeId              string        `protobuf:"bytes,1,opt,name=purgeId,proto3" json:"purgeId,omitempty"`
	Status               string        `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Errors               []*PurgeError `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SinglePurgeResult) Reset()         { *m = SinglePurgeResult{} }
func (m *SinglePurgeResult) String() string { return proto.CompactTextString(m) }
func (*SinglePurgeResult) ProtoMessage()    {}
func (*SinglePurgeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c901454c9c027c0e, []int{1}
}

func (m *SinglePurgeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SinglePurgeResult.Unmarshal(m, b)
}
func (m *SinglePurgeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SinglePurgeResult.Marshal(b, m, deterministic)
}
func (m *SinglePurgeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SinglePurgeResult.Merge(m, src)
}
func (m *SinglePurgeResult) XXX_Size() int {
	return xxx_messageInfo_SinglePurgeResult.Size(m)
}
func (m *SinglePurgeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SinglePurgeResult.DiscardUnknown(m)
}

var xxx_messageInfo_SinglePurgeResult proto.InternalMessageInfo

func (m *SinglePurgeResult) GetPurgeId() string {
	if m != nil {
		return m.PurgeId
	}
	return ""
}

func (m *SinglePurgeResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SinglePurgeResult) GetErrors() []*PurgeError {
	if m != nil {
		return m.Errors
	}
	return nil
}

type PurgeError struct {
	ErrorCode            string   `protobuf:"bytes,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PurgeError) Reset()         { *m = PurgeError{} }
func (m *PurgeError) String() string { return proto.CompactTextString(m) }
func (*PurgeError) ProtoMessage()    {}
func (*PurgeError) Descriptor() ([]byte, []int) {
	return fileDescriptor_c901454c9c027c0e, []int{2}
}

func (m *PurgeError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurgeError.Unmarshal(m, b)
}
func (m *PurgeError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurgeError.Marshal(b, m, deterministic)
}
func (m *PurgeError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurgeError.Merge(m, src)
}
func (m *PurgeError) XXX_Size() int {
	return xxx_messageInfo_PurgeError.Size(m)
}
func (m *PurgeError) XXX_DiscardUnknown() {
	xxx_messageInfo_PurgeError.DiscardUnknown(m)
}

var xxx_messageInfo_PurgeError proto.InternalMessageInfo

func (m *PurgeError) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *PurgeError) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*PurgeReuslt)(nil), "myproto.PurgeReuslt")
	proto.RegisterType((*SinglePurgeResult)(nil), "myproto.SinglePurgeResult")
	proto.RegisterType((*PurgeError)(nil), "myproto.PurgeError")
}

func init() { proto.RegisterFile("proto/myproto/PurgeResult.proto", fileDescriptor_c901454c9c027c0e) }

var fileDescriptor_c901454c9c027c0e = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8d, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x89, 0x21, 0x09, 0xb9, 0x71, 0xe3, 0x55, 0x64, 0x10, 0xc1, 0x30, 0xab, 0x80, 0x10,
	0x41, 0x7d, 0x03, 0x71, 0xe1, 0x42, 0x91, 0xe9, 0xaa, 0xcb, 0x94, 0x0c, 0xa1, 0x30, 0xed, 0x84,
	0xf9, 0x59, 0xf4, 0xed, 0xcb, 0xdc, 0x4c, 0x9a, 0x96, 0xae, 0x86, 0x73, 0xbe, 0x7b, 0xe6, 0x83,
	0x97, 0xd1, 0x68, 0xa7, 0xdf, 0x76, 0x87, 0xe9, 0xfd, 0xf7, 0x66, 0x90, 0x42, 0x5a, 0xaf, 0x5c,
	0x4b, 0x0d, 0x16, 0x11, 0xf1, 0x35, 0x54, 0x91, 0x7a, 0xab, 0x1c, 0x3e, 0x40, 0xe6, 0xb4, 0xeb,
	0x14, 0x4b, 0xea, 0xa4, 0xc9, 0xc4, 0x14, 0xf0, 0x13, 0x0a, 0x43, 0x6b, 0xcb, 0x6e, 0xea, 0xb4,
	0xa9, 0xde, 0x9f, 0xda, 0xb8, 0x6f, 0x57, 0xdb, 0xfd, 0xa0, 0xe4, 0x99, 0x40, 0xcc, 0xa7, 0xdc,
	0xc0, 0xdd, 0x15, 0x45, 0x06, 0xc5, 0x18, 0xe2, 0x4f, 0x4f, 0x8a, 0x52, 0xcc, 0x11, 0x1f, 0x21,
	0xb7, 0xae, 0x73, 0x3e, 0x38, 0x02, 0x88, 0x09, 0x5f, 0x21, 0x97, 0xc6, 0x68, 0x63, 0x59, 0x4a,
	0xee, 0xfb, 0x93, 0x9b, 0xfe, 0xfd, 0x0e, 0x4c, 0xc4, 0x13, 0xfe, 0x07, 0xb0, 0xb4, 0xf8, 0x0c,
	0x25, 0xf5, 0x5f, 0xba, 0x97, 0x51, 0xb7, 0x14, 0xc8, 0xe1, 0x96, 0xc2, 0xaf, 0xb4, 0xb6, 0x1b,
	0x64, 0xd4, 0x5e, 0x74, 0x9b, 0x9c, 0x4c, 0x1f, 0xc7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x3e,
	0x09, 0x1e, 0x51, 0x01, 0x00, 0x00,
}
